"""Experiment A: reanalyse completed E2A carrier-local functional footprints."""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path

import numpy as np

from tools.carrier_access_audit.protocol import TAIL_CLASSES, frozen_protocol
from tools.carrier_access_audit.statistics import (
    effective_count,
    normalized_positive_entropy,
    weighted_mean,
    weighted_pairwise_cosine_diversity,
)
from tools.client_update_audit.protocol import frozen_protocol as e2_protocol
from tools.semantic_acquisition.common import file_sha256, write_csv, write_json


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not Path(path).is_file():
        raise FileNotFoundError(path)
    with Path(path).open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def _truth(value: str) -> bool:
    return str(value).strip().lower() in {"1", "true", "yes"}


def _validate_e2a(e2a_dir: Path) -> dict:
    contract_path = Path(e2a_dir) / "runtime_contract.json"
    if not contract_path.is_file():
        raise FileNotFoundError(contract_path)
    contract = json.loads(contract_path.read_text(encoding="utf-8"))
    if contract.get("stage") != "e2a" or contract.get("server_aggregation_called") is not False:
        raise RuntimeError("Experiment A requires a completed pre-aggregation E2A runtime")
    if contract.get("protocol") != e2_protocol():
        raise RuntimeError("E2A runtime was not generated by the frozen 80--99 E2 protocol")
    fairness = _read_csv(Path(e2a_dir) / "runtime_fairness.csv")
    if not fairness or any(not _truth(row["pass"]) for row in fairness):
        raise RuntimeError("E2A runtime fairness contains failed clients")
    return contract


def analyse(e2a_dir: Path, output_dir: Path) -> dict:
    e2a_dir, output_dir = Path(e2a_dir), Path(output_dir)
    contract = _validate_e2a(e2a_dir)
    all_rows = _read_csv(e2a_dir / "local_all_class_footprints.csv")
    tail_rows = _read_csv(e2a_dir / "local_tail_metrics.csv")

    vectors: dict[tuple[int, str, int], np.ndarray] = {}
    supported_mask: dict[tuple[int, str, int], np.ndarray] = {}
    grouped_all: dict[tuple[int, str, int], list[dict]] = defaultdict(list)
    for row in all_rows:
        if int(row["local_epoch"]) != 3 or row["condition"] != "natural":
            continue
        key = (int(row["data_seed"]), row["topology"].lower(), int(row["client_id"]))
        grouped_all[key].append(row)
    for key, rows in grouped_all.items():
        ordered = sorted(rows, key=lambda row: int(row["class_id"]))
        if [int(row["class_id"]) for row in ordered] != list(range(100)):
            raise RuntimeError(f"Client does not contain one 100-class footprint: {key}")
        vectors[key] = np.asarray([float(row["margin_gain"]) for row in ordered], dtype=np.float64)
        supported_mask[key] = np.asarray([_truth(row["locally_supported"]) for row in ordered], dtype=bool)

    tail_final: dict[tuple[int, str, int, int], dict] = {}
    for row in tail_rows:
        if int(row["local_epoch"]) == 3 and row["condition"] == "natural":
            key = (
                int(row["data_seed"]), row["topology"].lower(),
                int(row["client_id"]), int(row["tail_class"]),
            )
            tail_final[key] = row

    carriers: dict[tuple[int, str, int], list[tuple[int, int]]] = defaultdict(list)
    for (seed, topology, client_id, tail_class), row in tail_final.items():
        mass = int(row["tail_sample_count"])
        if mass > 0:
            carriers[(seed, topology, tail_class)].append((client_id, mass))

    per_class = []
    for (seed, topology, tail_class), values in sorted(carriers.items()):
        client_ids = [client_id for client_id, _ in values]
        masses = np.asarray([mass for _, mass in values], dtype=np.float64)
        client_vectors = [vectors[(seed, topology, client_id)] for client_id in client_ids]
        coverages = [float(np.mean(vector > 0)) for vector in client_vectors]
        entropies = [normalized_positive_entropy(vector) for vector in client_vectors]
        unsupported_coverages = []
        for client_id, vector in zip(client_ids, client_vectors):
            unseen = ~supported_mask[(seed, topology, client_id)]
            unsupported_coverages.append(float(np.mean(vector[unseen] > 0)) if unseen.any() else 0.0)
        worst_neighbor = [
            float(tail_final[(seed, topology, client_id, tail_class)]["worst_neighbor_margin_gain"])
            for client_id in client_ids
        ]
        matrix = np.stack(client_vectors)
        per_class.append({
            "data_seed": seed,
            "topology": topology,
            "tail_class": tail_class,
            "carrier_count": len(client_ids),
            "effective_carrier_count": effective_count(masses),
            "tail_sample_count": int(masses.sum()),
            "tail_mass_weighted_positive_all_class_margin_coverage": weighted_mean(coverages, masses),
            "tail_mass_weighted_positive_unseen_class_margin_coverage": weighted_mean(unsupported_coverages, masses),
            "tail_mass_weighted_positive_gain_entropy": weighted_mean(entropies, masses),
            "tail_mass_weighted_worst_neighbor_margin_gain": weighted_mean(worst_neighbor, masses),
            "cross_carrier_functional_cosine_diversity": weighted_pairwise_cosine_diversity(matrix, masses),
            "carrier_union_positive_margin_coverage": float(np.mean(np.any(matrix > 0, axis=0))),
            "carrier_intersection_positive_margin_coverage": float(np.mean(np.all(matrix > 0, axis=0))),
        })
    expected = {(42, topology, tail) for topology in ("dirichlet", "clientlt") for tail in TAIL_CLASSES}
    observed = {(row["data_seed"], row["topology"], row["tail_class"]) for row in per_class}
    if expected != observed:
        raise RuntimeError(f"Experiment A units differ from frozen seed-42 protocol: missing={sorted(expected-observed)}")

    by_unit = {(row["data_seed"], row["topology"], row["tail_class"]): row for row in per_class}
    metrics = [
        "effective_carrier_count",
        "tail_mass_weighted_positive_all_class_margin_coverage",
        "tail_mass_weighted_positive_unseen_class_margin_coverage",
        "tail_mass_weighted_positive_gain_entropy",
        "tail_mass_weighted_worst_neighbor_margin_gain",
        "cross_carrier_functional_cosine_diversity",
        "carrier_union_positive_margin_coverage",
    ]
    contrasts = []
    for tail_class in TAIL_CLASSES:
        left = by_unit[(42, "dirichlet", tail_class)]
        right = by_unit[(42, "clientlt", tail_class)]
        row = {"data_seed": 42, "tail_class": tail_class}
        for metric in metrics:
            row[f"dirichlet_minus_clientlt__{metric}"] = float(left[metric] - right[metric])
        contrasts.append(row)

    summary_metrics = {}
    for metric in metrics:
        values = np.asarray([row[f"dirichlet_minus_clientlt__{metric}"] for row in contrasts])
        summary_metrics[metric] = {
            "direction": "dirichlet_minus_clientlt",
            "mean": float(values.mean()),
            "median": float(np.median(values)),
            "positive_tail_classes": int((values > 0).sum()),
            "tail_class_count": len(values),
        }
    breadth_keys = [
        "tail_mass_weighted_positive_all_class_margin_coverage",
        "tail_mass_weighted_positive_gain_entropy",
        "tail_mass_weighted_worst_neighbor_margin_gain",
        "carrier_union_positive_margin_coverage",
    ]
    supported_metrics = [
        name for name in breadth_keys
        if summary_metrics[name]["mean"] > 0 and summary_metrics[name]["positive_tail_classes"] >= 12
    ]
    verdict = "DIRICHLET_CARRIERS_FUNCTIONALLY_BROADER" if len(supported_metrics) >= 2 else "NO_CONSISTENT_CARRIER_FOOTPRINT_GAP"
    output_dir.mkdir(parents=True, exist_ok=True)
    write_csv(output_dir / "experiment_a_per_tail_class.csv", per_class)
    write_csv(output_dir / "experiment_a_paired_contrasts.csv", contrasts)
    summary = {
        "experiment": "A",
        "verdict": verdict,
        "descriptive_only": True,
        "supported_breadth_metrics": supported_metrics,
        "metrics": summary_metrics,
        "protocol_hash": frozen_protocol()["protocol_hash"],
        "e2a_theta0_hash": contract["theta0_hash"],
        "input_hashes": {
            name: file_sha256(e2a_dir / name) for name in (
                "runtime_contract.json", "runtime_fairness.csv",
                "local_all_class_footprints.csv", "local_tail_metrics.csv",
            )
        },
        "evidence_boundary": (
            "Natural Client-LT versus Dirichlet carrier-local association before aggregation; "
            "client size, steps, class composition and exposure are intentionally not matched."
        ),
    }
    write_json(output_dir / "experiment_a_summary.json", summary)
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--e2a-dir", type=Path, default=Path("output/e2_client_update_audit/e2a_local_footprint"))
    parser.add_argument("--output-dir", type=Path, default=Path("output/carrier_access_audit/experiment_a"))
    args = parser.parse_args()
    print(json.dumps(analyse(args.e2a_dir, args.output_dir)))


if __name__ == "__main__":
    main()
